coverage_service: coveralls
workspace: Motif.xcworkspace
xcodeproj: Motif.xcodeproj
scheme: Motif-iOS
ignore:
  - Motif/Objective-C Runtime/*
  - Motif/iOS Support/UIColor+HTMLColors.m
  - Motif/Core/MTFErrors.m
  - Carthage/*
  - ../*
